### ISSUE TITLE
Side Left Pouch

### ISSUE THREAD

**Issue by runcreeper** [ForgottenGlory/Dungeons-Deviousness#1]
When equiped it unequips the main body armor.
Can be repeated via going into the helgen cave and putting on imperial armor then an imperial side left pouch.

This also applies to bikini armor thongs and their chest pieces.

**Comment by ForgottenGlory** [comment]
This is, unfortunately, a known issue between bandoliers and TAWOBA/Devious Devices. It's possible that setting the Device Hider slot in the Devious Devices MCM to disabled would fix it, but otherwise I'm not aware of a fix.
