### ISSUE TITLE
Embers HD patch has updated

### ISSUE THREAD

**Issue by tiemetess** [ForgottenGlory/Dungeons-Deviousness#10]
Installation seems to be failing because the sneak tools ember HD patch was updated today.

https://www.nexusmods.com/skyrimspecialedition/mods/1863/?tab=files&navtag=https%3A%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fajax%2Fmoddescription%2F%3Fid%3D1863%26preview%3D1

**Comment by ForgottenGlory** [comment]
I know.
