### ISSUE TITLE
Jenassa Black face

### ISSUE THREAD

**Issue by ignazflam** [ForgottenGlory/Dungeons-Deviousness#100]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&D Version**
Beta 2

**Describe the bug**
Jenassa has a Black face

**To Reproduce**
Look at her

**Expected behavior**
Skin color of face should match the skin color of the body

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
