### ISSUE TITLE
NPC's Nude vs. Clothed Different

### ISSUE THREAD

**Issue by Asmondar** [ForgottenGlory/Dungeons-Deviousness#101]
It appears that (at least for me) the nude bodies are not matching the clothed bodies. For instance in my game Gerder looks to be wearing 100 weight clothes, but when naked, she looks like 0 weight. 

I used the DL files and I also tried rebuilding using the instructions.

[nudity removed]

**Comment by Asmondar** [comment]
It appears that (at least for me) the nude bodies are not matching the clothed bodies. For instance in my game Gerder looks to be wearing 100 weight clothes, but when naked, she looks like 0 weight. 

I used the DL files and I also tried rebuilding using the instructions.

**Comment by ForgottenGlory** [comment]
Depending on the NPC this may be correct. Some have a unique body (the Gman NPCs come to mind) that doesn't conform to typical bodyslide generation. Fill out a proper bug report with NPC IDs and such using the issue template.
