### ISSUE TITLE
Bandit triggering trap in Bleak Falls Barrow leads to ctd

### ISSUE THREAD

**Issue by ignazflam** [ForgottenGlory/Dungeons-Deviousness#102]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&D Version**
beta 2 (and beta 1)

**Describe the bug**
InBleak Falls Barrow when you sneak next to bandit who is going to trigger trap and die I recieve ctd. I remember this error was present in beta 1 too

**To Reproduce**
Sneak to the bandit and wait till he activates the lever and dies

**Expected behavior**
Bandit should activate the lever not ctd

**Comment by ForgottenGlory** [comment]
invalid without crashlog
