### ISSUE TITLE
Ninirim Collection book generates infinite money

### ISSUE THREAD

**Issue by ignazflam** [ForgottenGlory/Dungeons-Deviousness#105]
**D&D Version**
beta 2 and before

**Describe the bug**
[SunJeong] Ninirim Collection 5.0 book allows you to generate gold out of nothing.

**To Reproduce**
grab book craft no material armors sell it buy leather strips and start making +40% sneaking boots.

**Expected behavior**
Armors shuold have at materials required related with final value. If not they should have perk prerequesitives or value should be reduced. Eventually the book can be hidden in more remote place like hall of the heroes in sovengarde.

**Additional context**
I am aware this is known bug.

**Comment by ForgottenGlory** [comment]
Imperfectly fixed beta 3, needs a revision but should do for now
