### ISSUE TITLE
Monk knock down allows to stun merchants and steal everything

### ISSUE THREAD

**Issue by ignazflam** [ForgottenGlory/Dungeons-Deviousness#106]
**D&D Version**
beta 2

**Describe the bug**
Monk knockdown allows to stun merchants steal everything and recieve no bounty

**To Reproduce**
Approach merchant, knock him down and take everything from the shop

**Expected behavior**
The knockdown should not be 100% effective. It should be a crime

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
