### ISSUE TITLE
Way of the Monk doesn't follow Simply Balanced Framework

### ISSUE THREAD

**Issue by Vhostym** [ForgottenGlory/Dungeons-Deviousness#108]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[D&DDC Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&DDC Version**
Beta 2

**Describe the bug**
The Simply Balanced Framework causes all damage sources at low levels to do about 2-5 points of damage on a normal hit (depending on feats and other factors). In contrast, Way of the Monk unarmed damage is routinely doing 15-30 points of damage depending on enemy armor, which does not seem to be your intent.

**To Reproduce**
Steps to reproduce the behavior: Create a monk class character, use the unarmed skill and compare that to your damage using a sword, or magic.

**Expected behavior**
I expected the damage to be similar to that of a normal weapon, potentially slightly ahead due to my character being built as a monk. Instead it's about 3-5 times better, at level 1.

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/6604675/saves.zip)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
