### ISSUE TITLE
Armor missing in Bodyslide armor group

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Dungeons-Deviousness#109]
The **Daring Fur Armor** (**G3B Fur Armor** 1-4 in Bodyslide) is not in the armor group and won't get generated when building own bodyslides, resulting in a invisible body.
The **G3B Blade Armor** could also be affected, it's listed in the Unassigned Group but i haven't checked

Currently playing Beta 2

![G3B Fur Armor](https://user-images.githubusercontent.com/85462940/120943377-c60b8980-c72e-11eb-9ebe-2ba2af7551a8.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
