### ISSUE TITLE
body ignoring bodyslide preset with specific clothing, while the clothing does not

### ISSUE THREAD

**Issue by TheKaldra** [ForgottenGlory/Dungeons-Deviousness#111]
**D&DDC Version**
D&DDC Beta 2

**Describe the bug**
Body does not match specified preset or armor worn when I equip "red micro bikini"

**To Reproduce**
Equip "red micro bikini" or any clothing from the same mod it seems

**Expected behavior**
body matches set bodyslide preset and armor

**Screenshots**
![enb2021_6_7_15_58_33](https://user-images.githubusercontent.com/73563177/121080814-ed536c80-c7a9-11eb-96b4-dd457f53681f.png)

**Additional context**
screenshot of armor not matching in-game, in bug screenshot channel

**Comment by ForgottenGlory** [comment]
Fixed beta 3
