### ISSUE TITLE
Body's not Matching clothed vs. nude.

### ISSUE THREAD

**Issue by Asmondar** [ForgottenGlory/Dungeons-Deviousness#112]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[D&DDC Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&DDC Version**
Put the version of the list you are on here.
Current Version Beta 2

**Describe the bug**
There are several npc's that when stripped of clothing, their bodies are different than when in armor or clothes. It looks like a standard zero weight body. But they have 100 weight when clothed.

**To Reproduce**
Load game and play with bodyslide files dl'd from Pins.

**Expected behavior**
Expected that unclothed bodies should match/be close to the clothed bodies.

**Screenshots**
Unable to post due to would require nudity.

***DO NOT PUT NUDITY ON GITHUB***

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.
Toccata Base c0000d62 / Ref C0009419
Lydia Base A2C9E / Ref A2C94
Gerdur 1347c / 13489
Camilla Valerius 1347b / 13488
Sigrid 13476 / 13483
Delphine 13478 / 13485
Adrianne Avenicci 13bb9 / 1a67c
Danica Pure-Spring 13ba5 / 1a69f
Carlotta Valentia 13b99 / 1a675
Arcadia 13ba4 / 1a66d
Hulda 13ba3 / 1a66e
Uthgerd the Unbroken 918e2 / 91918
Saadia 13ba2 / d7505
Olfina Gray-Mane 13b9b / 1a685
Aela 1a696 / 1a697
Njada Stonearm 1a6d9 / 1a6da
Ysolda 13bab / 1a69a
Irileth 13bb8 / 1a67f
Fianna d16dd / d16e2
Gerder c247e / d16e1
Ahlam 13bbe / 1a6a5

**Additional context**
There are more, but these were who I found in Whiterun and Riverwood. It seems to be the "important npc's" Generic like guards and mercenary and tavern wench seem unaffected. I hope this is a better report.

**Comment by ForgottenGlory** [comment]
Fixed for all affected NPCs (yes, even those not on your list. List is much appreciated though) for Beta 3.
