### ISSUE TITLE
MME Milk Cuirass missing additional Bodyslide options

### ISSUE THREAD

**Issue by Eikonoklaste** [ForgottenGlory/Dungeons-Deviousness#113]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[D&DDC Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&DDC Version**
Beta 3

**Describe the bug**
MME_MilkCuirass only shows Slim2Thicc in the preset selection dropdown.

**To Reproduce**
Open Bodyslide, choose 1.DNDDC Clothes from groups, then input "milk" into the outfit search and select MME_MilkCuirass in Outfit/Body dropdown.

**Expected behavior**
The expectation is to see other slider presets like The Legendary Booty Body - Princess as an available option in the Preset dropdown menu

**Screenshots**
![image](https://user-images.githubusercontent.com/85655234/121449187-ee79ca80-c95e-11eb-9b43-2986202509c7.png)

***DO NOT PUT NUDITY ON GITHUB***

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Someone with a bit more knowledge of Outfit Studio and such is gonna have to look at this. Normally there's a JSON or similar file that lists all the different presets the outfit works with. In the meantime, you can work around this by selecting a different outfit and batch building the MilkCuirass with that other outfit and a preset selected, whatever preset you select for the other outfit should then apply to the MilkCuirass.

**Comment by celadoneiron** [comment]
https://discord.com/channels/690583538210308106/822807131312095252/856854968315936778

3BA BodySlide file here should work with presets without problems.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 6
