### ISSUE TITLE
Arbor Philosophorum & Wild Concoctions load order, updates

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Dungeons-Deviousness#114]
**D&DDC Version**
Beta 3.

**Describe the bug**
Arbor Philosophorum is positioned above Vokrii in the load order, forcing Vokrii to load earlier than intended. (Not currently an issue, but could cause issues in future versions if something gets inserted between them that needs to be overridden by Vokrii instead of overriding it.)

Some Wild Concoctions changes are overridden by iWant RND for CACO right now. Wild Concoctions needs to load after all iWant RND plugins. There's also an update with additional fixes and tweaks (removed duplicate recipes, prevented unintended EXP gain from CACO auto-conversion recipes that made levelling up way faster than it should have been). I've also shared a file in the dev patches channel that prevents Dynamic Food from renaming Charred Meat back to Charred Skeever Meat.

**To Reproduce**
Go to a cooking pot with raw meat from animals other than skeevers in your inventory. "Charred Skeever Meat" will be available to cook from those meats.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
