### ISSUE TITLE
Dark face bug witch start npc

### ISSUE THREAD

**Issue by DaveMcMuffin** [ForgottenGlory/Dungeons-Deviousness#116]
**D&DDC Version**
Beta 3

**Describe the bug**
Black face bug on the NPC that you find in the witch den start from the Content Consumer's Alternate Starts

**To Reproduce**
Enter the witch start in the alternate start and use the witch start in the content consumer's alternate start sub menu

**Expected behavior**

**Screenshots**
![enb2021_6_10_17_07_04](https://user-images.githubusercontent.com/85693589/121549703-6226e080-ca0e-11eb-9a86-73923c755064.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
