### ISSUE TITLE
DX Necromancer Robes not transparent

### ISSUE THREAD

**Issue by jorghei** [ForgottenGlory/Dungeons-Deviousness#118]
**D&DDC Version**
Beta 4

**Describe the bug**
DX Necromancer Robes - The transparent robes are not transparent

**To Reproduce**
Skull to unlock recipe in Windhelm Hall of the Dead, craft Transparent robes (any color), all will look the same as regular version

**Expected behavior**
You get it

**Screenshots**
![image](https://user-images.githubusercontent.com/45927085/121792838-b3c69b00-cbc7-11eb-8c98-9a05fa2ca395.png)

Item code:
![image](https://user-images.githubusercontent.com/45927085/121792859-fbe5bd80-cbc7-11eb-8d76-447b84451a31.png)

**Comment by ForgottenGlory** [comment]
Working for me, not sure what went wrong here. The transparency is _extremely_ subtle.
