### ISSUE TITLE
Clockwork Castle enemies go invisible for some (most?) sex animations

### ISSUE THREAD

**Issue by BadGitNoDonut** [ForgottenGlory/Dungeons-Deviousness#119]
**D&DDC Version**
Beta 3

**Describe the bug**
Lose to Gilded or Gilded Husk enemies in the Clockwork Castle content and most (but not all) sex animations result in the main body of the NPC in question becoming invisible. All that's left are the heads, bracers, and boots. 

**To Reproduce**
Fight. Lose. Get fucked.

**Expected behavior**
Non-invisible sexual partners.

**Screenshots**
That would NOT be safe for work. :)

**Comment by ForgottenGlory** [comment]
So the Gilded are a custom creature specifically added by Clockwork and they don't have a NSFW body mesh available that I'm able to find. Short of making one (which I unfortunately have neither the skill nor talent to do), I don't think it's possible to fix this. Would be happy to include a fix if one is found.
