### ISSUE TITLE
Unable to download Ember HD Patch-1863-0-1-Beta-1559201165.rar

### ISSUE THREAD

**Issue by Msmrme** [ForgottenGlory/Dungeons-Deviousness#12]
**D&D Version**
Alpha 5 (Latest)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Try to download the modlist

**Expected behavior**
Files to download 

**Screenshots**
![Ember Tools](https://user-images.githubusercontent.com/63477201/89717381-c3f46500-d97b-11ea-908b-108519b73585.png)
![Wabbajack Error](https://user-images.githubusercontent.com/63477201/89717394-f1411300-d97b-11ea-968a-c819c397ec22.png)

**Additional context**
I'm doing the manual download without Nexus Premium, everything is else downloaded fine but when I restart the download it directs me to install Sneak Tools 0.6A. There is also an Ember HD patch that updated 8/7/2020 underneath it so the list may just need to be updated for the new file.

**Comment by ForgottenGlory** [comment]
I know.
