### ISSUE TITLE
Missing hair from high poly npc 

### ISSUE THREAD

**Issue by DaveMcMuffin** [ForgottenGlory/Dungeons-Deviousness#120]
**D&DDC Version**
Beta 4

**Describe the bug**
High poly npc replacer missing hair or at least I assume they do, the one I found is at the "I am an addict in a skoma den start.

**To Reproduce**
Do the "I am an addict in a skoma den" start when you choose your start and then talk to the lady that gives you the redwater skoma

**Expected behavior**
I expect people to have hair on their head, especially females.

**Screenshots**
![enb2021_6_13_19_56_34](https://user-images.githubusercontent.com/85693589/121817515-2eec8780-cc82-11eb-9a34-79b5e65641a4.png)

**Comment by ForgottenGlory** [comment]
This particular NPC is supposed to be bald. If you find others, please report them as you did this one.
