### ISSUE TITLE
Jordis the Sword-Maiden

### ISSUE THREAD

**Issue by Nordmann92** [ForgottenGlory/Dungeons-Deviousness#121]
**D&DDC Version**
Beta 4

**Describe the bug**

when i start at the Silver-Blood Inn, Jordis the Swords-Maiden gets killed by everyone

**To Reproduce**

Start Option:
- I am a patron at a local inn
- Silver-Blood Inn (Markarth)
Then:
- go to the Bar
- wait a few seconds
- Jordis engages and try to attack something/ the dog?
- she gets killed by everyone inside

**Expected behavior**
she doesnt attacks/gets killed

**Comment by ForgottenGlory** [comment]
Working as intended.
