### ISSUE TITLE
MCM / Realistic Needs

### ISSUE THREAD

**Issue by Nordmann92** [ForgottenGlory/Dungeons-Deviousness#122]
**Section**
Beta 4
MCM / Realistic Needs

**Description**
"
Realistic Needs
   Basic Needs
   Click Start RN&D, then exit the MCM and then go back into it.
"

Realistic Needs was already started, no need to click "Start RN&D"

**Comment by ForgottenGlory** [comment]
False.

**Comment by Nordmann92** [comment]
yup, sry i loaded an old save and messed up.
my fault sry
