### ISSUE TITLE
Male Guards have no Armor

### ISSUE THREAD

**Issue by Nordmann92** [ForgottenGlory/Dungeons-Deviousness#123]
**D&DDC Version**
Beta 4

**Describe the bug**

Male Guards wearing no Armor

**To Reproduce**
My Start Option:
- I am a patron at a local inn
- Silver-Blood Inn (Markarth)
Then:
- go outside
(- attack event of the woman happens)

guards dont wear armor

**Expected behavior**

Male Guards should wear Armor i guess?

**Comment by Banzaibear** [comment]
Also in my install

D&DDC Version
Beta 4

Describe the bug

Male Guards wearing no Armour

To Reproduce
My Start Option:

    I am a patron at a local inn
    Devious enslaved - pirates (Solitude exit)
    Then:
    Escape - make way to Solitude, then take wagon to Whiterun.

Guards are naked. When I checked their inventory, they had no armour - just pants, which do not equip with "equipitem" command. 

Expected behavior

Armoured guards

**Comment by BadGitNoDonut** [comment]
Just to chime in, I tried the 'Prostitute in Riverwood' start and while I didn't think to look at anyone Guardish in Riverwood, when I got to Whiterun there were a buncha naked guards.

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
