### ISSUE TITLE
Adding a Table of Contents to the readme

### ISSUE THREAD

**Issue by Listerw** [ForgottenGlory/Dungeons-Deviousness#125]
**Section**
It'd be nice to have a section at or near the start of the D&DDC readme that links to the different sections of it, just like the LS3 readme does.

**Description**
A table of contents would help in quickly navigating the readme.

**Comment by ForgottenGlory** [comment]
The todo, it burnsssss

Will do when I get a chance.

**Comment by ForgottenGlory** [comment]
Done
