### ISSUE TITLE
Follower framework sell items key is unbound after MCM configuration

### ISSUE THREAD

**Issue by Listerw** [ForgottenGlory/Dungeons-Deviousness#126]
**D&DDC Version**
Beta 4 - Though I also saw this in Beta 3.

**Describe the bug**
After following the MCM configuration, the Follower Framework sell items key is left unbound, but the keymap shows that it should be bound to U.

**To Reproduce**
On a new game, go to MCM > Follower Framework > System > Load from File.
Other keys will be bound but the follower sell items is left unbound.

**Expected behavior**
The follower sell items key should be bound to U, matching what the keymap shows.

**Comment by ForgottenGlory** [comment]
Intended, will update keymap.
