### ISSUE TITLE
Nipple Piercings not aligned properly

### ISSUE THREAD

**Issue by Crosser0987** [ForgottenGlory/Dungeons-Deviousness#127]
D&DDC Version
Beta 3 and still persistent in Beta 4

Describe the bug
Nipple Piercings are floating above characters nipples instead of being in them. This happens while using the pre-build bodyslides and the piercings were given to my character by a devious follower and are from the Devious Lore mod if that helps.

To Reproduce
Equip nipple piercings on character.

Expected behavior
The piercings being inside the nipple not floating around them.

**Comment by ForgottenGlory** [comment]
Partially fixed Beta 5. They'll function correctly while nude but some outfits may still have them behave oddly (as per the readme).
