### ISSUE TITLE
Radiant Prostitution in Whiterun sends you to hostile NPCs in locked homes

### ISSUE THREAD

**Issue by BadGitNoDonut** [ForgottenGlory/Dungeons-Deviousness#128]
**D&DDC Version**
Beta 4

**Describe the bug**
Doing Home Delivery quests in the Bannered Mare, I was repeatedly sent to either 'Thief' in Uthgerd's house or 'Assassin' in Breezehome. The former is locked with inhabitants (including Thief) who attempt to kill you if you break in, and the latter is a touch hard to access at level 3, but if you console your way in, the assassin does indeed attempt to murder you.

This behavior has so far only occurred to me on the first run of home delivery; if I give up and wait for another one, it seemed to work as per normal.

I won't be at my home PC for a few days, but if it's still relevant by then I can provide a save once I get home again.

**To Reproduce**
Go to the Bannered Mare
Fuck enough people to open up Home Deliveries in Radiant Prostitution.
Accept the first Home Delivery.

**Expected behavior**
A radiant prostitution target that wants to fuck you or have you fucked, not shove a sword through your spine. Also one that's in an accessible location.

**Comment by ForgottenGlory** [comment]
Upon further review and consideration, this is on-theme for the list and seems appropriate. Won't fix.
