### ISSUE TITLE
Skill tree values do not match

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Dungeons-Deviousness#129]
**D&DDC Version**
Beta 3 and 4

**Describe the bug**
After character creation the values in the upper and lower skill tree screen do not match. For example, altmer with +10 illusion (reflect) and illusion as a class pick starts with 25 in the perk tree visual, and in the grid below it is 45. 

**To Reproduce**
Tried on Dark elf, redguard and others - occurs on all of them

**Expected behavior**
The values should match.

**Comment by celadoneiron** [comment]
Not a bug. The bonuses to skill values are _bonuses_, like a Fortify Skill effect. Your base skill values do not change. This is intended. The difference between the two skills screens are showing them with bonuses (which affects things like damage scaling) and without (the level that determines whether or not you're able to choose a perk).

**Comment by Banzaibear** [comment]
Thanks
