### ISSUE TITLE
Pelagia Farm Fences non solid objects

### ISSUE THREAD

**Issue by DaveMcMuffin** [ForgottenGlory/Dungeons-Deviousness#130]
Hello FG today we are playing a game called "Is it a modlist bug or is it just skyrim being more broken than I remember it being 10 years ago"

**D&DDC Version**
Beta 4

**Describe the bug**
The top beams in the fences at Pelagia Farm (the farm near whiterun where the companions fight the troll) aren't solid objects

**To Reproduce**
Visit Pelagia Farm and walk through some of the farm fences where the bottom beam is close to the ground

**Expected behavior**
Fences are usually made for stopping things (tbh it might just be skyrim doing its thing I am not sure if vanilla does this)

**Screenshots**
![enb2021_6_15_16_22_56](https://user-images.githubusercontent.com/85693589/122070096-f7065100-cdf5-11eb-834c-0c35942d6b9f.png)

**Additional context**
Loving the list FG <3

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
