### ISSUE TITLE
Roggvir's execution Stuck

### ISSUE THREAD

**Issue by DaveMcMuffin** [ForgottenGlory/Dungeons-Deviousness#131]
**D&DDC Version**
Beta 4

**Describe the bug**
Roggvir scripted execution doesn't play out and everyone just stands around and shouts at him and captain Aldis dialogue doesn't start.

**To Reproduce**
Visit Solitude for the first time

**Expected behavior**
Roggvirs head should be chopped off because he is a filthy traitor

**Comment by ForgottenGlory** [comment]
Unable to replicate
