### ISSUE TITLE
Hearing repeated melee strike sounds (sounds like sword damage?) long after combat ceases.

### ISSUE THREAD

**Issue by wswank13** [ForgottenGlory/Dungeons-Deviousness#132]
**D&DDC Version**
Beta 3

**Describe the bug**
After finishing combat (or during combat, though this is harder to parse) sword striking sounds repeat at random for some time (5-30 seconds).  They are at max volume so seem to be targeted on the player.  Have only tested with Bound Sword due to early game difficulty in obtaining items - not certain if this will apply to other weapons.

**To Reproduce**
1) Summon Bound Sword
2) Engage in combat.
3) End combat by killing enemies.  With bound sword sheathed or unsheathed, repeated damage sounds will be heard.

**Expected behavior**
This should probably not be happening.

**Comment by ForgottenGlory** [comment]
Unable to replicate

**Comment by HoloBlades** [comment]
had this issue in beta 4 with the bound dagger, specifically I was also using the freezing strikes spell with the smart cast so it was cast when I drew the dagger
