### ISSUE TITLE
Devious Lore incompatibility (DCL, Beast Race Refits)

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Dungeons-Deviousness#134]
**D&DDC Version**
Beta 4 (and previous).

**Describe the bug**
Devious Lore is causing issues with multiple other mods and base DD functions.

Deviously Cursed Loot: MCM settings are ignored when traps are triggered. Devices that have been disabled will still appear and be force-equipped, and maximum device count settings are not respected. Multiple players experiencing the issue (including me). More details from NumberXer0 in Discord: "Is there another place in the MCM that overwrites the Cused Loot settings? Because they really don't seem to do shit. I have my max devices set to 3 and some of them turned off, yet I loot a body and got stuck with 6 devices..including ones I disabled." [This issue has been reported in the LL thread for Devious Lore](https://www.loverslab.com/topic/110619-devious-lore/?do=findComment&comment=3273839).

BRRF: Many devices are invisible on non-"human" races (elves, orcs, Khajiit, Argonians). Devious Lore makes changes to the Editor IDs of a huge number of Devices, with the vast majority of these records being otherwise identical to the master. This overrides changes from Beast Race Refits and the SE patch and reverts the records back to the default, removing the links to the additional BRRF armour addons. The default DD armour addons themselves are still affected by BRRF and are no longer available to elves, orcs, and beast races, resulting in affected devices being invisible on those races.

Dirty/incorrect edits: Devious Lore removes necessary keywords from some devices, which prevents appropriate animations from playing by incorrectly flagging some devices as being chastity devices when they aren't. These changes are inconsistent (e.g. applying only to one colour variation of one outfit, with the other two remaining as in base DD).

**To Reproduce**
Turn off a bunch of devices in the DCL MCM, or reduce the maximum devices allowed to equip at once, and then trigger a trap.
Equip one of many head restraints (e.g. Black Waxed Ring Gag) as an Argonian, Khajiit, Orc, or Elf - restraint will be invisible.
Equip one of several body restraints (e.g. White or Red Leather Topless Straightjacket) - animations will be filtered as if wearing a chastity device.

**Expected behavior**
MCM settings should dictate game behaviour.
Devices should be visible when equipped.
Devices should allow appropriate animations to play.

**Comment by ForgottenGlory** [comment]
Devious Lore removed Beta 5
