### ISSUE TITLE
Minor Bug: enslaved start on the Pirate ship 

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Dungeons-Deviousness#136]
**D&DDC Version**
Beta 4

**Describe the bug**
There are two ships, one on top of the other - one is moving (rocking in the sea), one is not. Not a major bug, as you do not spend long here. 

**To Reproduce**
Go to solitude, the ship is to the north, along the path from the docks. Tried it in beta 3 and 4 on different starts, same double ship. 

**Expected behavior**
One ship is enough

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 5
