### ISSUE TITLE
Missing meshes - Lingerie set

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Dungeons-Deviousness#137]
Probably already reported, but here is another minor glitch. 

**D&DDC Version**
Beta 4

**Describe the bug**
Only the bodyslide file is installed for the "Lingerie Set - CBBE - 3BBB - BodySlide Physics" by Alunder.

**To Reproduce**
Noticed the backpack which contains the lingerie was missing from Alvor's house in Riverwood. 

**Expected behavior**
Needs the "Lingerie Set CBBE Curvy" installed to work.

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
