### ISSUE TITLE
Don't set OutputDataPath in DnDDC\mods\BodySlide and Outfit Studio\CalienteTools\BodySlide\Config.xml

### ISSUE THREAD

**Issue by t3h0th3rLL** [ForgottenGlory/Dungeons-Deviousness#139]
**Section**
[Bodyslides - Build Your Own](https://www.fgsmodlists.com/dddc#h.1o5fsk63tr09)

**Description**
Instead of setting the output path in Bodyslide - Options > Advanced to the actual path 
this setting can be omitted so no manual intervention is needed, MO2 output redirection is sufficient to

WJ apparently correctly takes care that GameDataPath points to the correct steam installation location (or i was very lucky), but OutputDataPath isn't set correctly in DnDDC\mods\BodySlide and Outfit Studio\CalienteTools\BodySlide\Config.xml:

<GameDataPath>c:\steam\steamapps\common\Skyrim Special Edition\data\</GameDataPath>
<OutputDataPath>C:\Modlists\D&DDC\mods\BodyslideOutfitStudio - Overwrite</OutputDataPath> <- 

If OutputDataPath is set, but points to a nonexistent path (or one which exists, but isn't where the D&DDC\mods are located, the generated meshes aren't available in game.

OutputDataPath  doesn't have to be set though, if it's left empty, the output redirection of MO2 works just fine (because it overlays steamapps\common\Skyrim Special Edition\data in the vfs).

So <OutputDataPath></OutputDataPath> works just fine, and one less thing users can get wrong by not reading the manual :D

**Comment by t3h0th3rLL** [comment]
I put this in readme improvements, but obviously the setting in the config needs to be removed, before the readme can be modified.

**Comment by ForgottenGlory** [comment]
Done Beta 5
