### ISSUE TITLE
Shandar follower not appearing

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Dungeons-Deviousness#140]
**D&DDC Version**
Beta 4.

**Describe the bug**
The follower Shandar doesn't appear in the Dead Man's Drink in Falkreath.

**To Reproduce**
1. Go to the Dead Man's Drink in Falkreath.
2. Look for an absence of Shandar.

**Expected behavior**
Shandar should be there.

**Additional context**
ShandarStandaloneFollower.esp is positioned before ShandarStandaloneFollowerCore.esp in the load order. Moving ShandarStandaloneFollower.esp so that it's after the Core.esp made him show up. (I don't know why this makes a difference. Maybe because they both have the same BSA attached? All I know is, he's not there until I switch the order around, and then he is.)

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
