### ISSUE TITLE
USSEP outdated

### ISSUE THREAD

**Issue by OceanFifty** [ForgottenGlory/Dungeons-Deviousness#141]
**Version**
Latest version  (13 June)

**Describe the bug**
Wabbajack points to an older version of USSEP, which is no longer available for download.

26,28 - File hash check (-42) cb3ba8c707a3b215bea37c5b117fd4938374a500559cf2e1d85c7b7a3435a89c
26,35 - Downloading Unofficial Skyrim Special Edition Patch-266-4-2-5a-1623034459.7z

**Comment by ForgottenGlory** [comment]
lol
