### ISSUE TITLE
ussep got updated, new users cant download the list

### ISSUE THREAD

**Issue by ENDERNIKEHu** [ForgottenGlory/Dungeons-Deviousness#142]
As the title says, ussep got an update from 4.2.5a to 4.2.5b, and the old version got deleted from nexus, so wabbajack is unable to detect the file.
![kép_2021-06-23_155438](https://user-images.githubusercontent.com/86363065/123109187-4faf9c80-d43b-11eb-949f-9f4b053ce432.png)

**Comment by ForgottenGlory** [comment]
K
