### ISSUE TITLE
Update NFF, adjust install order

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Dungeons-Deviousness#145]
Nether's Follower Framework has updated to 2.7.7, with several bug fixes as well as added features. This should help with import/export issues and eyes/hair going invisible with in stealth, in particular.

Also, the current install order overwrites NFF's 3DNPC patch scripts with the default 3DNPC scripts, but it should be the other way around.

**Comment by ForgottenGlory** [comment]
Done Beta 6
