### ISSUE TITLE
Duplicate .esps in Outfits Merged

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Dungeons-Deviousness#146]
**D&DDC Version**
Beta 5.

**Describe the bug**
There are non-stacking unique versions of the same items in the same places because there are multiple differently-named plugins for the same mods included in Outfits Merged.

edit: also, the different versions of the same items can't be used interchangeably in crafting recipes.

The files in question are:
"Celes Rogue Armor CBBE.esp",
"Celes Rogue Armor UNP.esp",
"Celes Tarot Outfit Cloth CBBE.esp",
"Celes Tarot Outfit Cloth UNP.esp",

**To Reproduce**
Go to the Ragged Flagon in Riften and pick up the Celes Rogue crafting manuals, black leather, and black dye. There will be two different versions of each.

**Expected behavior**
No duplicates.

**Screenshots**
![Screen Shot 06-26-21 at 00 07 001](https://user-images.githubusercontent.com/73095714/123499642-79ef9d00-d67b-11eb-81b1-7c8140e531a5.PNG)
![Screen Shot 06-26-21 at 00 07](https://user-images.githubusercontent.com/73095714/123499646-7cea8d80-d67b-11eb-9971-b2d7dac1b411.PNG)

**Additional context**
The Witcher 3 outfits added by TW3_femaleArmors_zzjay.esp are all also included in Divine Elegance, but I think they have different names, so it's not quite as obvious. Still, that mod may not be necessary any more, I think that Divine Elegance has all the same outfits but with more colour variations.

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
