### ISSUE TITLE
Nipple piercing not "sticking" to nipples when nude

### ISSUE THREAD

**Issue by Zephyrai** [ForgottenGlory/Dungeons-Deviousness#147]
**D&DDC Version**
Beta 5

**Describe the bug**
When nude the nipple piercings are not attached to the nipples. They roughly follow up and down mostly but will with basically any moved on the breasts no longer be attached until they come to a standstill. Even while standing still the idle animation will ofter move the breasts and also end up with floating piercings

**To Reproduce**
Equip nipple piercing (used soul gem piercing)
be nude
move around/wait on idle animations 
look at breasts in 3rd person

**Expected behavior**
The piercings stay attached to the nipples

**Screenshots**
Posted 2 gyazo gifs links in dnddc-bugs-screenshots.

***DO NOT PUT NUDITY ON GITHUB***

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Was on a completly new character just out of the starting cell.

**Comment by t3h0th3rLL** [comment]
I came across this issue too, and found out, that this can be fixed by selecting groups [0. DNDDC Bodies] and [1. DNDDC Clothes] and then picking the [Devious Devices CBBE 3BA] Variants of the piercings, when batch building. I reckon the [DDX - CBBE SE] variants contained in group [1. DNDDC Clothes] are left there by mistake.

**Comment by ForgottenGlory** [comment]
Good find, thank you. Fixed Beta 6.
