### ISSUE TITLE
Meridia is hair

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Dungeons-Deviousness#149]
**D&DDC Version**
Beta 5.

**Describe the bug**
Meridia is hair.

**To Reproduce**
Find the beacon, return it to the pedestal, get lifted, observe wig.

**Expected behavior**
Meridia is not hair.

**Screenshots**

![Screen Shot 07-02-21 at 21 39 001](https://user-images.githubusercontent.com/73095714/124269512-4e3e4c80-db7e-11eb-801f-8437d43c662b.PNG)

**Comment by ForgottenGlory** [comment]
but... but how

**Comment by BadGitNoDonut** [comment]
Can reproduce, ran into this myself.

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
