### ISSUE TITLE
Flyaway Nipples

### ISSUE THREAD

**Issue by CaseyAnthonyWeiner** [ForgottenGlory/Dungeons-Deviousness#15]
**D&D Version**
Alpha 5

**Describe the bug**
The more sex the player character has, the nipples get more and more elevated. I think maybe it's related to Fill Her Up/SLIF but not sure.

**To Reproduce**
1) Have lots of sex in the game
2) Observe

**Expected behavior**
Nipples should not fly away. If you quit the game and reload it, they reset to normal.

**Screenshots**
https://imgur.com/a/hNrETaF

**Additional context**

**Comment by Grokstreet** [comment]
Seconding this report. SLIF / Fill Her Up does seem the likely culprit as sex increased the issue. But for me it only really started after being forced into becoming a Milk Maid so that could be it as well.

**Comment by ForgottenGlory** [comment]
Might be fixed Alpha 7, followup on this

**Comment by CaseyAnthonyWeiner** [comment]
I checked tonight, still seems to be going on. I'm still not sure what is causing it though. Definitely some morph, and it resets if you exit the game and come back.
