### ISSUE TITLE
Radiant Prostitution not recognizing client orgasm

### ISSUE THREAD

**Issue by Eikonoklaste** [ForgottenGlory/Dungeons-Deviousness#150]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[D&DDC Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&DDC Version**
Beta 6

**Describe the bug**
Satisfying a client during Radiant Prostitution free roam quest doesn't recognize client orgasm from SLSO or basic "Sexlab always orgasm" settings, resulting in not being paid despite the fact that they've orgasmed (sometimes multiple times).

This was a known issue that was supposedly fixed with Radiant Prostitution 7.0.2 (Beta), but has only now appeared in D&D:DC. This was not present in the previous Beta 5 release of D&D:DC.

**To Reproduce**

1. Go to an Innkeeper and ask for work
2. Take work as a prostitute
3. Find clients and satisfy them
4. See that no matter how many orgasms they have, the mod tells you the customer didn't cum and won't pay you

**Expected behavior**
Expectation is to be paid after making a client orgasm.

**Screenshots**

***DO NOT PUT NUDITY ON GITHUB***

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
