### ISSUE TITLE
SLA Exposure not changing

### ISSUE THREAD

**Issue by OrzoSavo** [ForgottenGlory/Dungeons-Deviousness#151]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[D&DDC Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&DDC Version**
Beta 6

**Describe the bug**
Having sex with anyone won't result in a change in the SLA Exposure, i.e. starting at 15 exposure, no orgasm, end with 15 (or 16 due to time change) exposure

**To Reproduce**
Initiate sex with any NPC and let the scene play out

**Expected behavior**
Exposure to have increased or reset due to having an orgasm during sex

**Screenshots**

***DO NOT PUT NUDITY ON GITHUB***

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
[D&DDC Save.zip](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/6759137/D.DDC.Save.zip)

**Comment by hatter-gaming** [comment]
Having this issue too. Just did a fresh wabbajack install and made a new character and I'm still having the issue. By the time MCM setup was done, arousal was at 46 as displayed by both the SLA widget and the message given by the show arousal key (N). Held N to initiate a SL solo animation two times. The exposure displayed by the SLA widget never changed. Here's a screenshot of the SLA status in the MCM after that: 
![Skyrim Special Edition 5_07_2021 19_53_36](https://user-images.githubusercontent.com/86896378/124453829-1e37b900-ddcb-11eb-9399-3d4e7231297d.png)

As you can see, 46 arousal is coming from somewhere not shown by SLA, and it isn't being effected by the satisfaction. Just for testing purposes, also used the 'Tie me up!' DCL debug option to see if the Bondage stat works as expected, and it does: 
![Skyrim Special Edition 5_07_2021 20_00_26](https://user-images.githubusercontent.com/86896378/124454435-d1a0ad80-ddcb-11eb-816d-904ef1290928.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
