### ISSUE TITLE
AVA & Elsa setup

### ISSUE THREAD

**Issue by Eikonoklaste** [ForgottenGlory/Dungeons-Deviousness#155]
**Section**
AVA & Elsa
Less Intrusive HUD
Sexlab
SL Anim Loader

**Description**
_AVA & Elsa_ — Bolded suggestion to wait to set these up until after leaving the start cell.
_Less Intrusive HUD_ — Exit menu and let the setup fully complete before continuing
_Sexlab_ — Exit the menu and wait until you see "creature animations installed" before continuing (this can sometimes come up more than once, so best to wait an additional 30 seconds after the message fades to ensure nothing else pops up)
_SL Anim Loader_ — If this takes too long to open, close the MCM and wait 30 seconds before trying again

**Comment by ForgottenGlory** [comment]
Done, except for AVA/ELSA part - I have no indication that there is a benefit to waiting until after the start cell to do these.
