### ISSUE TITLE
Collar issue with Sexual Fame 

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Dungeons-Deviousness#181]
**D&DDC Version**
2.0

**Describe the bug**
Sexual Fame puts collars into the inventory of 'submissive' Npcs and they equip it, running around with a slave collar

**To Reproduce**
-

**Expected behavior**
Free the people of Skyrim! (Looks stupid if random Npcs are running around with a collar)

**Screenshots**
-

**Additional context**
Deactivate the option in SL Fame seems to fix it
Sexlab - Sexual Fame > Customization Npc > Equipment for naked Submissive > Allow Re-Equip

**Comment by ForgottenGlory** [comment]
Duplicate of #183
