### ISSUE TITLE
Lip/facial expression is not syncing during a sex scene, plus eyes are not blinking problem

### ISSUE THREAD

**Issue by tdktwan** [ForgottenGlory/Dungeons-Deviousness#184]
D&DDC Version
2.1.1

Describe the bug
Bug 1. Lips not syncing/mouth/facial expression not working properly during a sex scene.
Bug 2. eyes not blinking the whole time, only blink once when you enter the racemenu.

To Reproduce
For Bug 1. Play a sex scene.
For Bug 2. Enter the game.

Expected behavior
For Bug 1. Either the face stays plane and dead with just one motion, or the mouth open and close repeatedly, which is abnormal.
For Bug 2. Should blink.

Additional context
For lips/mouth issue, I found a solution by 1. downloading the scripts from: https://www.loverslab.com/topic/139270-the-still-prevalent-lip-sync-issue/, place sslBaseExpression.pex in the sexlab script folder.  2. uncheck the SL Better BJ in OM2 because it can overwrite the sslBaseExpression.pex script. 3. Place sslBaseVoice.pex in Separate Orgasm script folder. 4. Open Sexlab Framework MCM, enable play lip sync animation. This should fix the issue.

For the eye blinking issue, download the mfg fix https://www.nexusmods.com/skyrimspecialedition/mods/11669 should fix this issue.

P.S 1: SL Better BJ author made an edit for LE that contains skse dll and also installs a ini file after launching, no port for se https://www.loverslab.com/topic/144650-sexlab-better-blowjobs/page/2/?tab=comments#comment-3027852

P.S 2: SL Better BJ now been replaced in Sexlab Framwork BETA9.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
