### ISSUE TITLE
Werewolfs have a double penis

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Dungeons-Deviousness#185]
**D&DDC Version**
2.1

**Describe the bug**
During scenes werewolfs grow a second, bigger dick (could be from the giant werewolfs)

**To Reproduce**
Start a scene with a werewolf

**Expected behavior**
One dick is enough to take my dignity

**Screenshots**
https://discord.com/channels/690583538210308106/848246716792176660/882414082433613855

**Comment by zarantha** [comment]
I hope I'm not stepping on any toes here.

Try disabling werewolves in either the Creature Framework MCM or in the SOS MCM. They should only be active in one. 

On the MNC threads, it's usually recommended to disable werewolves in SOS. It will need to be disabled for each male schlong in SOS (so both smurf and vector). 

If you want to disable in CF instead, werewolves are usually in multiple places, so you'd need to go through each page under creatures. For this list, it looks like just pages 8 (werewolf) and 17 (werebear).

**Comment by ForgottenGlory** [comment]
Zarantha is correct.
