### ISSUE TITLE
Not able to leave prison area.

### ISSUE THREAD

**Issue by Cuzlow** [ForgottenGlory/Dungeons-Deviousness#187]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[D&DDC Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&DDC Version**
2.1.1

**Describe the bug**
I select starting point from statue and when I click on the bed the screen goes black and then I return to the prison area.

**To Reproduce**
I guess start a new game?

**Expected behavior**
Can not leave prison area

**Screenshots**
N/A

***DO NOT PUT NUDITY ON GITHUB***

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by TheCampingOwl** [comment]
Read the pins in the discord server for the gameplay help channel.

**Comment by Cuzlow** [comment]
Thank you.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
