### ISSUE TITLE
Filling water at cooking pot replaces vessels with a Jug

### ISSUE THREAD

**Issue by Listerw** [ForgottenGlory/Dungeons-Deviousness#189]
**D&DDC Version**
2.1.1

**Describe the bug**
When you are cooking and use the water recipe, it replaces your empty vessels with a jug of water. If you already have a partially full jug of water, it adds another one.

**To Reproduce**
1. Obtain an empty waterskin
2. Go to the Bannered Mare and use the cooking pot
3. Craft the Water recipe

This will result in a full Jug with water instead of a waterskin.

**Expected behavior**
The waterskin should be filled with boiled water.

**Additional context**

**Comment by celadoneiron** [comment]
This is not a bug. This is how CACO works with crafting water and water tokens.

**Comment by Listerw** [comment]
Alright, I'll close this, since it sounds like even if it isn't how the modlist would ideally behave, it's not changeable anyway. And so there's no point in keeping a bug open that won't be solved.
