### ISSUE TITLE
SL Parasite - Quest skip (Fixed in Ver. 2021-07-31)

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Dungeons-Deviousness#193]
**D&DDC Version**
2.1

**Describe the bug**
Eating a spider egg skips the Chaurus Queen quest to stage 3. (Fixed in Ver. 2021-07-31)

**To Reproduce**
Chug down a spider egg (gross)

**Expected behavior**
No quest skip

**Screenshots**
-

**Additional context**
-

**Comment by zarantha** [comment]
2021-07-31 version is here:
https://www.loverslab.com/topic/120107-skyrimlldeepbluefrog-mods-conversion-to-sse/?do=findComment&comment=3462496

Bodyslide version as of now is v7, provided that link in the dev channel.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
