### ISSUE TITLE
Riverrun Smeltry

### ISSUE THREAD

**Issue by runcreeper** [ForgottenGlory/Dungeons-Deviousness#2]
**D&D Version**
1st Release
**Describe the bug**
Riverun Smeltry overlapping a waterwheel

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot281](https://user-images.githubusercontent.com/6655116/87990655-4d112e00-ca99-11ea-85b4-160c82ed31e8.png)

**Comment by ForgottenGlory** [comment]
Fixed Alpha 2
