### ISSUE TITLE
Restraints not in inventory

### ISSUE THREAD

**Issue by jtmoney412** [ForgottenGlory/Dungeons-Deviousness#20]
**D&D Version**
Alpha 5

**Describe the bug**
Sometimes when restraints are put on me - by my devious follower, loot, surrendering, etc. - some of the restraints show up on my body, but not in my inventory. It's then impossible - as far as I know - to remove them.

**To Reproduce**
Steps to reproduce the behavior: This has happened a few times, but most recently I had my follower tie me up and got the same problem. I asked my follower to get me out of the devices (she put a lot on me) and she did successfully take everything off, except for the armbinders and harness. I then asked her to untie my hands (that was the option) and she said she would, but then I got an error "[DDH] WornDevice is None" - I also tried equipping other arm-binders (just to see what happens) and it said I can't have multiple on simultaneously. 

**Expected behavior**
I assume all restraints show up as equipped in the inventory so you can attempt to unlock them and/or ask someone to help remove them.

**Screenshots**

![ScreenShot286](https://user-images.githubusercontent.com/62395499/89949866-8bac8b00-dbf6-11ea-870c-2418a50cb9b0.png)
![ScreenShot284](https://user-images.githubusercontent.com/62395499/89949881-936c2f80-dbf6-11ea-878a-d7024d0042dd.png)
![ScreenShot285](https://user-images.githubusercontent.com/62395499/89949910-9d8e2e00-dbf6-11ea-854b-138d3e4ea9bc.png)

**Additional context**
I didn't take a screenshot before having the initial set of restraints removed, but they included gloves and I think something that wouldn't conflicted with the harness.

**Comment by ForgottenGlory** [comment]
Known issue with Devious Devices unfortunately, only solution I know of is to reload before you got the restraints.
