### ISSUE TITLE
DCL: Combat Surrender for player still enabled

### ISSUE THREAD

**Issue by CaseyAnthonyWeiner** [ForgottenGlory/Dungeons-Deviousness#22]
**D&D Version**
Alpha 7

**Describe the bug**
The imported MCM settings for DCL still have player combat surrender enabled. Just adding a reminder here to disable that for the next release so you can track it.

**Comment by ForgottenGlory** [comment]
Thanks, knew I was forgetting something.

**Comment by ForgottenGlory** [comment]
Fixed pre-release build 1
