### ISSUE TITLE
Wabbajack instalation stops because of enbseries_skyrimse_v0463.zip

### ISSUE THREAD

**Issue by Marvozz** [ForgottenGlory/Dungeons-Deviousness#220]
**D&DDC Version**
i have no idea where to find it, since log not mention it
Wabbajack Version: 2.5.3.1
mod version downloaded today (31.10.2021)

**Describe the bug**
Unable to download enbseries_skyrimse_v0463.zip (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/enbseries_skyrimse_v0463.zip_0eba6cb9-ace6-439c-aa69-cd9f8054df28)
Cannot continue, was unable to download one or more archives

Newest maintenance changed nothing in that regard. And the fun part is, that enbseries_skyrimse_v0463.zip was downloaded by wabbajack - i have it in download folder (wabbajack says that hashed download is incorrect).

**To Reproduce**
Dunno, try to install from scratch?

**Expected behavior**
Instalation stops on downloading enb files

**Comment by DrFrosty21** [comment]
You can get the enbseries files in #dnddc-install-support on discord (pinned message).
But the list is still in maintenance, Wabbajack is just weird and shows it as available.

**Comment by Marvozz** [comment]
Thanks. Downloaded and it solved the problem. 
To any future viewers - remember to pick your role (game type) in #role-assigment. Only then you'll have access to file.
But since it's maintenance anyway, i'll wait with full instalation.

Any estimates when downtime ends?
