### ISSUE TITLE
Wabbajack was unable to continue (due to updated files)

### ISSUE THREAD

**Issue by Dalfbeta** [ForgottenGlory/Dungeons-Deviousness#221]
Wabbajack halted. Three files couldn't be downloaded.
Enbseries as mentioned in another issue, _Yamete! V3.1.7z_ and _SexLab-Separate-Orgasm-SE 1.7.3 SL1.63b9.7z_. 
Seems that Yamete! has been updated to V3.2 last wednesday. V3.1 is not available any more. Same for Sexlab-separate-Orgasm that is updated last friday to version 1.7.4 and version 1.7.3 is no longer available.

[Wabbajack.current.log](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/7448473/Wabbajack.current.log)

**Comment by DrFrosty21** [comment]
You can get the enbseries files in #dnddc-install-support on discord (pinned message).
Regarding the other mods, the list is still in maintenance. Wabbajack is just weird and shows it as available even though it's not.

**Comment by Dalfbeta** [comment]
Sorted out the enbseries files just now (seen your comment in #220. (thanks).
