### ISSUE TITLE
Unlimited additional Perk Points.

### ISSUE THREAD

**Issue by INubl** [ForgottenGlory/Dungeons-Deviousness#227]
**D&DDC Version**
2.3.0

**Describe the bug**
Unlimited additional perk points.

**To Reproduce**
Player.setlevel (High level [Ex. lv80])  >  Player.setlevel (Low level [Ex. lv25])  >  Gain one level because of level disparity (Ex. going from lv80 to lv25)  >  Sleep to level up/be able to assign perk points > "By the Luck of the Nine I have gained an additional Perk Point" message keeps popping infinitely.

**Expected behavior**
To gain at MOST 1 additional perk point.

**Screenshots**
![ScreenShot547](https://user-images.githubusercontent.com/94116998/141300445-d8391c99-8068-48e6-9a83-e25d77beb236.png)

**Additional context**
Not entirely sure if it's related somehow but I've changed my "Sleep to Level up" mod settings to be able to level up and assign perks after 1 hour of sleep and without limit.
Note: I have changed that at the beginning of my playthrough and everything was working fine so far, the bug only started after setting my character's level to a lower level and sleeping afterwards.

**Comment by INubl** [comment]
It appears that perk points aren't the only thing that are increasing infinitely but also my Health, Magicka and Stamina! They're all increasing by the second!

**Comment by celadoneiron** [comment]
We're not going to try to fix a problem that you caused yourself by using console commands to do something bizarre that doesn't even fit into the realm of normal console use. This is a non-bug.
