### ISSUE TITLE
Fire Texture Bug

### ISSUE THREAD

**Issue by Sinful-Soles** [ForgottenGlory/Dungeons-Deviousness#23]
**D&D Version**
Alpha 7

**Describe the bug**
Strange fire textures. Only on a few objects, sleeping giant fire, floor braziers, and a few more who might share the same fire.

**To Reproduce**
Go to sleeping Giant inn and look at the fire, and other area's with fixed fire places.

**Expected behavior**
Normal Textures.

**Screenshots**
![ScreenShot287](https://user-images.githubusercontent.com/67134549/90654218-c1a8cb00-e205-11ea-81fb-743f8feb9e87.png)

**Additional context**
Not the only object in the game, otherwise console would be open but most fire area's seem to have this either this badly or much more subtle, for instance the fires from forges only have about 2 or 3 of these textures but very small where you have to look for them to find them.

**Comment by ForgottenGlory** [comment]
Fixed pre-release build 1
