### ISSUE TITLE
Setting MCM for True Armor before AVA can lead to slow motion attacks

### ISSUE THREAD

**Issue by Listerw** [ForgottenGlory/Dungeons-Deviousness#235]
**D&DDC Version**
2.3.5

**Describe the bug**
After setting up MCMs and then specific AVA attributes, attacks with a one-handed dagger move in slow motion.

**To Reproduce**

1. Create a new Breton

2. Set up the MCMs until you've completed at least True Armor (or gone further).

3. (Optional) Equip a dagger and notice the regular attack swing speed.

3. Set AVA attributes to give yourself 19 points of Agility - the base is 9, so this needs at least 10 points.

4. Equip a dagger and attack in slow motion.

Note that setting AVA attributes and prior to True Armor doesn't seem to have the same issue.

**Expected behavior**
AVA agility increases melee speed so attacks should be faster.
Alternatively, the MCM instructions should say to set AVA attributes before True Armor.

**Additional context**
[Here's a save file with MCMs set up to True Armor just being finished](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/7658210/saves.zip)
[Here's a save file set up just before you'd do the True Armor MCM](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/7658384/savesBeforeTrueArmor.zip)

I've tried a separate MCM run through setting up AVA after the full MCM and got the same result.

**Comment by ForgottenGlory** [comment]
It's almost like the MCMs should be done in the order presented like the MCM page says. Funny how that works.

**Comment by Listerw** [comment]
I think the MCM instructions are wrong then, since they say you can do this either now or later:

> Immediately after you create your character, you'll be prompted to assign your attributes using AVA. **You may do this now or later** by selecting the appropriate response when the popup appears. If you choose to do this later, you'll be given a power in your Powers/Shouts menu that you can activate to assign your attributes.

Emphasis mine. Maybe this could be changed to:

> Immediately after you create your character, you'll be prompted to assign your attributes using AVA. You must do this when the popup is shown as assigning attributes at a later time can cause bugs.

That way it's clear that assigning attributes at a later time is not an option.
