### ISSUE TITLE
Keep it clean removes devious devices

### ISSUE THREAD

**Issue by ZdunTwo** [ForgottenGlory/Dungeons-Deviousness#24]
**D&D Version**
Alpha 7
**Describe the bug**
Keep it clean removes locked devious devices when bathing or using bucket to remove clothes.

**To Reproduce**
Equip devious device and use soap

**Expected behavior**
Devices should not be unequiped

**Additional context**
devices are still equiped in the inventory menu

**Comment by ElusiveWatcher** [comment]
This ends up being an issue when accompanied by a Devious Follower, as they'll punish you with extra debt for taking a bath without their equipment on you. The only way to prevent that is leaving said Devious Follower outside of the bath cell.

**Comment by CaseyAnthonyWeiner** [comment]
I would be surprised if there's a way to fix this without a script patch, which I'm not aware of.

You could manually remove the non-DD items from your character and bathe maybe, if it will let you do it, rather than using the basket.
