### ISSUE TITLE
Outfits with 2BBB physics (solution inside)

### ISSUE THREAD

**Issue by cacophony-wj** [ForgottenGlory/Dungeons-Deviousness#27]
**D&D Version**
Current

**Describe the bug**
2BBB breast outfits causing bounces that, apparently, are a big problem for some people

**To Reproduce**
Create your character, bounce up and down, the breasts are linked (two bone) applying SMP object doesn't do much.
Take off tunic, breasts bounce separately (3BBB behavior), SMP has intended effect

**Expected behavior**
All outfits need 3BBB physics (apparently)

**Screenshots**
Not necessary

**Additional context**
Here's the best type of report, one with the solution. Nechrion created 3BBB versions of the 2BBB minidresses you are currently using. They are to be found in Lotus' mods directory as "Minidressses 3BBB by Nechrion" or something to that effect. Use those BodySlide files and it solves the problem. Confirmed by @NAT64#6790" in #d-n-d-support. If you don't have Lotus installed, I think Nechrion will give you the conversions. He still comes around sometimes.

**Comment by ForgottenGlory** [comment]
Fixed 1.0.1
