### ISSUE TITLE
Toll collector ignoring license settings

### ISSUE THREAD

**Issue by Zephyrai** [ForgottenGlory/Dungeons-Deviousness#29]
**D&D Version**
1.0.0 9/4/2020

**Describe the bug**
Walking close to a Toll collector North East of riften starts the force greet. Hold it there pumpkin and removes all your items that require a license normally when they are enabled. This happens even with the setting disabled and is the only Toll collector in riften that acts this way.

**To Reproduce**
-Walk up to said Toll collector and let him spot you

**Expected behavior**
He should not forcegreet and remove my stuff since the licenses are disabled.

**Screenshots**
Screenshot of NPC in question
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 09 10 - 17 45 16 72](https://user-images.githubusercontent.com/71088427/92757689-406cd000-f38e-11ea-94e3-5cb768a7f9de.png)

Savefile:
[Savefile.zip](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/5203063/Savefile.zip)

**Comment by ForgottenGlory** [comment]
Fixed 1.0.1
