### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by Sinful-Soles** [ForgottenGlory/Dungeons-Deviousness#3]
**D&D Version**
Beta 1

**Describe the bug**
Crash to Desktop.

**To Reproduce**
Scroll through body overlays. 

**Expected behavior**
No crash to Desktop, previews of the overlays.

**Additional context**
Could be a random Skyrim Bug.

[Crash_2020_7_20_21-25-58.txt](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/4950976/Crash_2020_7_20_21-25-58.txt)

**Comment by Sinful-Soles** [comment]
**UPDATE:** Seems to be the body overlays that are separated by body area, Arm, Legs, etc.
[Crash_2020_7_20_21-53-8.txt](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/4951030/Crash_2020_7_20_21-53-8.txt)

**Comment by ForgottenGlory** [comment]
Fixed Alpha 2
