### ISSUE TITLE
Whiterun Toll Collector (SL Survival) follows me around... everywhere

### ISSUE THREAD

**Issue by MysticDaedra** [ForgottenGlory/Dungeons-Deviousness#32]
**D&D Version**
1.0.0.0

**Describe the bug**
EDIT: Temporary fix by selecting the toll collector and using the disable command in the console. Not ideal, but did the trick!

After speaking to the Whiterun Toll Collector immediately after entering Whiterun for the first time, he began to follow me around everywhere. He even just teleported into a cave I was exploring, prompting this report. I _think_ I was wearing a ball gag when I spoke to him. 

I've tried to kill him via console, but he is registered as Essential. I didn't see a debug option in SL Survival to fix this. Also tried recycleactor, but didn't do anything except strip his armor.

**To Reproduce**
Enter Whiterun, immediately speak to the Toll Collector. Maybe wear a ball gag... don't remember. 

**Expected behavior**
I'd expect him to remain in Whiterun after speaking to him xD

**Screenshots**
Currently enslaved, so can't take a non-nude screenshot, sorry :(

**Additional context**
Any possible temporary fix, like advancing a hidden quest or something?

**Comment by ForgottenGlory** [comment]
At a minimum I'll need the base/ref ID received when selecting this NPC in the console so I can find the correct one.
