### ISSUE TITLE
Broken download for High_Poly_Head_v1.3_(SE).zip

### ISSUE THREAD

**Issue by MiDDiz** [ForgottenGlory/Dungeons-Deviousness#33]
**D&D Version**
Version 1.0.0

**Describe the bug**
Broken download for High_Poly_Head_v1.3_(SE).zip

**To Reproduce**
Just try to do a clean install of the modpack. 

**Expected behavior**
Normal downloading before installing the modpack

**Screenshots**
![image](https://user-images.githubusercontent.com/36573608/93026346-a7e08500-f605-11ea-8369-7a9b8a6b5b94.png)
![image](https://user-images.githubusercontent.com/36573608/93026351-b29b1a00-f605-11ea-889d-4fe4fcc7be73.png)

**Additional context**
Thank you for your work!

**Comment by ForgottenGlory** [comment]
I know.
