### ISSUE TITLE
Conflict with JK's Skyrim and Thunderchild Pillar of Lightning Shield

### ISSUE THREAD

**Issue by MysticDaedra** [ForgottenGlory/Dungeons-Deviousness#35]
**D&D Version**
1.0.0.0

**Describe the bug**
JK's Skyrim adds a small room (interior space) to the rear of the Windpeak Inn in Dawnstar. It just so happens that Thunderchild puts a shout pillar (Pillar of Lightning Shield) in the exact same space. You can't get close enough to the pillar to activate it, although TCL clipping works as a workaround.

**To Reproduce**
Travel to Dawnstar by your preferred method. Go to the REAR of the Windpeak Inn (southern side), follow the compass icon. Pillar of Lightning Shield is clearly inside the added components to the inn.

**Expected behavior**
Not sure how to resolve something like this. If the pillar was just moved slightly to the south, it could be in virtually the same position as normal, but not inside the inn.

**Screenshots**
![image](https://user-images.githubusercontent.com/17184148/93305703-bb315300-f7b3-11ea-8e25-0e5f59cc7211.png)
![image](https://user-images.githubusercontent.com/17184148/93305783-dc923f00-f7b3-11ea-9045-2b3215dc722c.png)

**Additional context**
No additional context. Doesn't appear to be any other mods in conflict here, but I'm no expert.

**Comment by ElusiveWatcher** [comment]
If I recall correctly, there was also a cellar door right next to the pillar, which led to the Clockwork Terminus.
