### ISSUE TITLE
Breast Physics Acting Weird

### ISSUE THREAD

**Issue by remski0131** [ForgottenGlory/Dungeons-Deviousness#36]
**D&D Version**
1.0.0

**Describe the bug**
Breast physics are being weird while armor/outfits are on

**To Reproduce**
Walk a little bit with armor/outfit equipped

**Expected behavior**
Physics to behave normally

**Screenshots**
![ScreenShot294](https://user-images.githubusercontent.com/52296669/93399003-7f3cd300-f831-11ea-8939-1955a91ab0fe.png)

**Additional context**
The problem only occurs with something equipped, The physics work normally when naked or when using bikini armors.

**Comment by ForgottenGlory** [comment]
Should be fixed 1.0.1

**Comment by remski0131** [comment]
armors still act this way in 1.0.1
