### ISSUE TITLE
NPC's have a dark skinned head when they should not.

### ISSUE THREAD

**Issue by Abstracthorror** [ForgottenGlory/Dungeons-Deviousness#37]
**D&D Version**
1.0.1

**Describe the bug**
NPC's have black face and it looks like a basic hairstyle. I'm currently in morthal and I saw three NPC's like this. The one in the screenshot is Benor

**To Reproduce**
Start new game, go to Morthal [it's the only place I have been]. Find Benor.

**Expected behavior**
NPC's to not have wrong color skin on one or more parts of the body.

**Screenshots**
![ScreenShot340](https://user-images.githubusercontent.com/71474944/93545100-38c8a080-f925-11ea-8b36-95b8a3245c32.png)

**Additional context**
The other two NPC's who had it ended up being fixed with a reload of the same save, but Benor has remained. One was a female guard the other was a woman who I can't remember the name of.

**Comment by Abstracthorror** [comment]
![ScreenShot341](https://user-images.githubusercontent.com/71474944/93547258-416fa580-f92a-11ea-8cc4-2ae2032e0d0e.png)
I uploaded the wrong screenshot, my bad.

**Comment by NotABitte** [comment]
Experiencing the same in Whiterun.
![ScreenShot289](https://user-images.githubusercontent.com/71539167/93658936-24ac9e00-fa0e-11ea-979a-d80818cf53af.png)
![ScreenShot290](https://user-images.githubusercontent.com/71539167/93658948-39893180-fa0e-11ea-8adc-3fb36999840d.png)
There were more but I lost them in the screenshot chase.

**Comment by ForgottenGlory** [comment]
Fixed 1.0.2
