### ISSUE TITLE
SLS keyword missing from bikini armor items

### ISSUE THREAD

**Issue by CaseyAnthonyWeiner** [ForgottenGlory/Dungeons-Deviousness#38]
**D&D Version**
1.0

**Describe the bug**
Some bikini armor items which are added from **Enemy Variations V4 - Items.esp** are missing SLS keywords. This prevents the bikini armor experience from working, as well as other SLS functionality. (ie: The bikini curse which is used by the license system. You don't have that enabled, by default, in this list.)

**To Reproduce**
Wear bikini armor and play. No experience is gained. You can verify this in the SLS MCM menu. You can also enable licenses, enable the bikini curse, then purchase a bikini armor license. Equip some of the bikini armors added by EV4 and you'll see the curse gets applied since the _SLS_BikiniArmor keyword is missing.

**Expected behavior**
I think you'd have to build a custom patch or use XEdit to add the necessary keywords.

**Screenshots**

Steel Bikini Top I from EV4
![image](https://user-images.githubusercontent.com/69488425/93639122-20f12b00-f9be-11ea-94ae-51fa9cd488f1.png)

Steel Bikini Top I from TAWoBA (and other patches)
![image](https://user-images.githubusercontent.com/69488425/93639044-015a0280-f9be-11ea-824c-44fdab25102d.png)

**Additional context**
The **SLS TAWOBAR Patch.esp** patch also only seems to include the keyword on tops and bottoms. I think for the experience functionality to work correctly (and the curse) you must be wearing only items tagged with that keyword. I'm not certain about that, though.

So the problem may be the Enemy Variations items as well as the non 32/52 slot items from the original mod as well.

**Comment by ForgottenGlory** [comment]
Fixed 1.0.2
