### ISSUE TITLE
Discussion: MilkMod morphs/SLIF

### ISSUE THREAD

**Issue by CaseyAnthonyWeiner** [ForgottenGlory/Dungeons-Deviousness#39]
**D&D Version**
1.0

**Describe the bug**
I've seen a few comments about MilkMod not increasing breast size, so I started messing around with it some trying to figure out why. There are a few different ways to do it.

The easiest way is to use the MilkMod Morph script changes from the mod author that you can find on LL. This is included in the list. I don't think the script update for RaceMenu morphs works with SLIF running as well though, which is why people aren't seeing changes. (I'm guessing they are overriding each other but not sure.)

The other way is SLIF only, but from what I've read there is either a disconnect with SLIF and 3BBB or it just doesn't work out of the box. Somebody on the LL forums created a bridge which allows you to map 3BBB morphs. I tinkered around with it, and it seems to work pretty well.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Additional context**
[MME Config Menu](https://www.loverslab.com/topic/101166-milk-mod-economy-se/?do=findComment&comment=3004374)

It takes some messing around with, but here's what I did.

1. Rebuilt all armors/body in BodySlide with a preset that is slim at weight 0 and thicccccc at weight 100. 
2. I took the high values from the XML and mapped them into a copy of the 002_CBBE_SE_Bodymorphs.json file included for SLIF
3. Added each of the breast morphs and its value from the xml/json file to the morph list in MME Config Menu under breast morphs
4. Tweaked the maximum breast scale (from 3 to 1.75) in MME
5. Adjusted the increase per milk/per level in MME (0.2, 0.1)

Now when my character gains milk, the breasts adjust as intended.

I probably spent way too much time on it, but it was bugging me that it wasn't working.

Also, there might be an easier way to get it to work but this is the only way I found. I think 3BBB throws a wrench in the gears maybe.

The bad part about this set up is that I don't think there's any way to import/save the morph lists in MME Config Menu. It's also going to be a bit subjective set up wise because everybody uses different bodies. Maybe you could set it up with your default body though and put the instructions into the MCM set up if you were so inclined.

Thanks for coming to my TED talk about lactating boobs in Skyrim.

**Comment by ForgottenGlory** [comment]
I'd be happy to test this out if you'd be willing to share the .json files you made/modified.

**Comment by CaseyAnthonyWeiner** [comment]
Sure, here are the SLIF files.
[skse.zip](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/5256644/skse.zip)

The values in this came directly from the "high weight" settings for the Summer preset in BodySlide. You can open that XML file and you'll see the slider names and the low/high values.

![image](https://user-images.githubusercontent.com/69488425/93791740-3d79a700-fbfa-11ea-9e86-06f131509dc8.png)

I think I also set my character weight to 0 in RaceMenu. I'm not sure what it would look like if the character weight was 100 and then you were applying the high weight morphs on top of that. It might not change at all or it might just look horrible.

There's definitely some exploration that could still be done on this. For me personally, the idea was that my character started out average, and then as she progressed through the MilkMod levels everything scales up. I haven't played with this set up enough from start to finish yet to know if that will work out, but I think it will. I'm also not sure how this would affect NPCs unless they were built with the same body mesh as the player.

Another potential route, if you're unhappy with the MilkMod integration, is Soulgem Oven. The new version works great, but unless there is a patch I don't think it would hook into Survival. You could potentially replace MilkMod and Egg Factory with SGO.

**Comment by ForgottenGlory** [comment]
I'm gonna keep working on this, won't make it into the next update (1.0.2) but maybe 1.0.3

**Comment by CaseyAnthonyWeiner** [comment]
That's cool. Just ping me if I can do anything.
