### ISSUE TITLE
Missing Clothing

### ISSUE THREAD

**Issue by runcreeper** [ForgottenGlory/Dungeons-Deviousness#4]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&D Version**
1st Release

**Describe the bug**
Transparent Catsuit High Heels Dont show up when on character. She just has invisible feet.
Using the Prebuilt Bodyslides

![ScreenShot285](https://user-images.githubusercontent.com/6655116/88009135-9f1c7880-cac6-11ea-89d7-d44e5de9f38f.png)

(Nudity removed)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
So, interestingly, these boots in particular don't have a bodyslide available to build so they show up as invisible. If anyone happens to have a bodyslide for the MXW_Catsuit heels then I can include it and build it to fix this.

**Comment by ForgottenGlory** [comment]
Might be fixed Alpha 3

**Comment by runcreeper** [comment]
To Fix you need to move the Foot_1.nif and Foot_0.nif from mods\Devious Devices\meshes\devious\zipsuit to \mods\BodySlide Output\meshes\Devious\zipsuit.
After Building Bodyslide. 
No Idea why bodyslide doesnt automatically grab them itself.
