### ISSUE TITLE
Unable to sell slaves

### ISSUE THREAD

**Issue by ray557913** [ForgottenGlory/Dungeons-Deviousness#46]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&D Version**
Most recent

**Describe the bug**
When I try to sell a female bandit I captured to the slave trader in riverwood it tells me I have no prisoners to sell

**To Reproduce**
Steps to reproduce the behavior: try to sell a prisoner

**Expected behavior**
To be able to sell my prisoner

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by CaseyAnthonyWeiner** [comment]
If you're talking about a bandit you captured by putting it in a sack, that is a Defeat feature. The Slave Trader in Riverwood is from Deviously Cursed Loot, and only buys NPCs captured via the combat surrender method of that mod.

**Comment by ray557913** [comment]
Thank you for that
