### ISSUE TITLE
"Dyndolod.esp is not found or too high in your load order"

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Dungeons-Deviousness#47]
**D&D Version**
1.1.0

**Describe the bug**
When I load a save I see the following message: "Dyndolod.esp is not found or too high in your load order". The save works and there does not seem to be any odd behaviour.

**Expected behavior**
I might reinstall, but wanted to check if I it was an issue with the standalone and resources. 

Cheers, great mod order, btw.

**Comment by ForgottenGlory** [comment]
Did you add any mods? Only way this would happen is if you did AFAIK.
