### ISSUE TITLE
Bikini armors have conflicting slots

### ISSUE THREAD

**Issue by MysticDaedra** [ForgottenGlory/Dungeons-Deviousness#51]
**D&D Version**
1.1.0

**Describe the bug**
The bikini armors have conflicting slots, specifically bottoms and tops. If you have a top equipped, you cannot have a bottom, and vice versa. 

**To Reproduce**
Try to equip both a bikini bottom and a bikini top. It won't let you.

**Expected behavior**
I'd like to be able to have a top and bottom both equipped at the same time :)

**Screenshots**
Screenshots wouldn't help I think. Too lazy to look in xEdit, sorry :( I'm assuming both bikini bottoms and tops were assigned to the same slot by accident (probably the body slot I'm guessing, slot 32).

**Additional context**
The only armor I've tested this issue with is Iron bikini armors, several variants.

**Comment by ForgottenGlory** [comment]
Not a bug, just SOS being dumb. Use the "Clean schlongified Armors" option in the SOS MCM.
