### ISSUE TITLE
Uthgerd the Unbroken Neck Seam

### ISSUE THREAD

**Issue by dollyReq** [ForgottenGlory/Dungeons-Deviousness#56]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&D Version**
Put the version of the list you are on here.

1.2.1

**Describe the bug**

Uthgerd the Unbroken's neck seam is off, her body is light and her head is dark like a Redguard.

**To Reproduce**

Enter the Bannered Mare.

**Expected behavior**

A normal seam or a seam that isn't so contrast.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![fbe91b2b084b4f11caaf63f7c04bdf95](https://user-images.githubusercontent.com/23082536/98453265-2f9ec780-214f-11eb-8967-d153863a7afb.jpg)

**Additional context**

**Comment by mael5trum** [comment]
I've got the same issue with Jenassa in The Drunken Huntsman.
Head textures are really dark.
