### ISSUE TITLE
Weird Texture/Overlapped

### ISSUE THREAD

**Issue by Sinful-Soles** [ForgottenGlory/Dungeons-Deviousness#6]
**D&D Version**
Alpha 3

**Describe the bug**
Floor is not where it should be.

**To Reproduce**
Go with egg start large bird or where you find the emerald dragon claw

**Expected behavior**
No overlapping floor/texture

**Screenshots**
![enb2020_7_24_20_26_45](https://user-images.githubusercontent.com/67134549/88447972-7a920a80-cdfe-11ea-8afe-019b40acf352.jpg)

**Additional context**
The floor does in fact have collision, need to jump to pass it. Minor bug however.

**Comment by ForgottenGlory** [comment]
Fixed pre-release build 1
