### ISSUE TITLE
Compass and Map issues

### ISSUE THREAD

**Issue by Tim0cracy** [ForgottenGlory/Dungeons-Deviousness#60]
Hello,

I downloaded the modlist and followed every rule I saw, but I have run into an issue.  I do not have a compass at all and when I try to open the map, I get a notification in the upper left hand corner saying "I do not have a map".   Occasionally, instead of instantaniously closing and saying "I do not have a map", it gives me a SkyUI error 5 message.

I tried redownloading the modlist to see if that was the issue, I redownloaded Skyrim itself, but nothing seems to be working.

I have checked the .ini files to make sure that the bShowCompass was set to = 1 and it was.

Before downloading the modlist, I uninstalled all previous information of skyrim and redownloaded it outside of the Project folder.

I'm kinda at my wits end and was wondering if anyone knew what could be going on.

**Comment by uzumakiangel9** [comment]
its part of a mod called sexlab survival, you need to purchase a map & compass from an npc general store

**Comment by ForgottenGlory** [comment]
Read the Readme.
