### ISSUE TITLE
Game crashes while loading saves after configuring MCM Menu

### ISSUE THREAD

**Issue by SamianDratniuk** [ForgottenGlory/Dungeons-Deviousness#61]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_12_3_15-33-26.txt](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/5637450/Crash_2020_12_3_15-33-26.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Save1_DFED8BAE_0_4172617961_AbandonedPrison01_000001_20201203131802_1_1.zip](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/5637508/Save1_DFED8BAE_0_4172617961_AbandonedPrison01_000001_20201203131802_1_1.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**D&D Version**
Put the version of the list you are on here.
1.2.2

**Describe the bug**
After I'm trying to load game right after configuring MCM Menu, game crashes. Saves before configuring do not crash.

**To Reproduce**
New game>character creation>configuring MCM with guide>save>load>crash

**Expected behavior**
To not crash

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
N/A
**Additional context**

**Comment by ForgottenGlory** [comment]
"New game>character creation>configuring MCM with guide>save>load>crash"

You need to save/load before configuring the MCMs.
