### ISSUE TITLE
Abigail CBBE futa doesn't work

### ISSUE THREAD

**Issue by TheCampingOwl** [ForgottenGlory/Dungeons-Deviousness#63]
If possible, please also attach a copy of your most recent save before the issue occurred.**
https://app.mediafire.com/b987mqwfv298h

**D&D Version**
 v1.3.0

**Describe the bug**
Futa animations don't function properly most of the time, the Futa component is missing from both the character and the PC, sometimes it works, sometimes it doesn't, nothing seems to cause it directly.

**To Reproduce**
Start any futa animation with NPC's, some will work, but most won't.

**Expected behavior**
The Futa component to be present.

**Screenshots**
Not possible due to nudity, not entirely sure where to even upload them.

**Additional context**
Ignore the title, I thought it was an abigail only issue, it seems that it is not. I have update the report accordingly.

**Comment by ForgottenGlory** [comment]
I believe this is related to the missing Billyy's AnimObjects ESP. Might be fixed 1.4.0

**Comment by TheCampingOwl** [comment]
Still happens in 1.4.0 with a couple animations, but we can use Gender Bender to get around it.
