### ISSUE TITLE
Realistic needs, Hunger not working as intended

### ISSUE THREAD

**Issue by TheCampingOwl** [ForgottenGlory/Dungeons-Deviousness#64]
**D&D Version**
1.3.0

**Describe the bug**
If you eat enough to reach the "Gluttony" stage, the hunger meter will freeze and never go down again.

**To Reproduce**
Eat until you get Gluttony

**Expected behavior**
The hunger meter to drop over time, like the other needs.

**Screenshots**
Not applicable.

**Additional context**
A solution I found to this is to disable realistic needs and enable it again, would a permanent solution be feasible or is it best to reload the mod when it inevitably fails?

**Comment by ForgottenGlory** [comment]
Fixed 1.4.0
