### ISSUE TITLE
Missing body

### ISSUE THREAD

**Issue by nbkLordLester** [ForgottenGlory/Dungeons-Deviousness#65]
**D&D Version**
1.3.0

**Describe the bug**
After getting caught and put into this specific outfit the body texture disappears along with some of the outfit. 

**To Reproduce**
Cannot reproduce as it is a random event
But I went with the prebuilt bodyslides
**Expected behavior**
I believe she's supposed to be nude under the skins
**Screenshots**
see discord

**Additional context**

**Comment by ForgottenGlory** [comment]
Looks like you never posted the screenshots to Discord, please do so and I'll look into this.

**Comment by nbkLordLester** [comment]
I think this was the same as the other ticket, I don't have the screenshots anymore but I'm not having the issue with the new version.
