### ISSUE TITLE
Maid of Skyrim Quest missing frost mirriam for tomato soup at remote camp

### ISSUE THREAD

**Issue by jawjadawg** [ForgottenGlory/Dungeons-Deviousness#66]
Maid of Skyrim Quest missing frost mirriam for tomato soup at the remote camp

**D&D Version**
v1.3.0

**Describe the bug**
The bag provided by Kasia does not include all the recipe ingredients

**Expected behavior**
Frost mirriam needs to be added to create tomato soup (000F431C)

**Comment by ForgottenGlory** [comment]
Fixed 1.4.0 - Tomato Soup no longer requires Frost Mirriam to craft.
