### ISSUE TITLE
Unlearning spells after using race menu

### ISSUE THREAD

**Issue by zwasi** [ForgottenGlory/Dungeons-Deviousness#67]
I've noticed that certain spells are removed from my spell book after using race menu/vanity mirror. So far the spells effected are flames, and healing hands.

**Comment by NumberXer0** [comment]
I can confirm. The exact two disappeared for me after using the "showracemenu" command. They can be easily added back, but would be nice if they didn't disappear in the first place.

**Comment by TheCampingOwl** [comment]
The spell "Sparks" can be added to this list.

**Comment by ForgottenGlory** [comment]
Inelegantly fixed 1.4.0
