### ISSUE TITLE
Missing texture (Fur Shoes)

### ISSUE THREAD

**Issue by CaseyAnthonyWeiner** [ForgottenGlory/Dungeons-Deviousness#70]
Noticed a few NPCs with shoe textures missing so I grabbed a screenshot of the item.

![image](https://user-images.githubusercontent.com/69488425/106084016-19b3f980-60e3-11eb-8039-be35fde780c8.png)

**Comment by CaseyAnthonyWeiner** [comment]
I saw some Stormcloak Guards with a bunch of missing textures too. I can grab a SS of those too if it's something you aren't aware of.

**Comment by ForgottenGlory** [comment]
Should be fixed 1.4.0
