### ISSUE TITLE
Billy Anim Objects ESP missing

### ISSUE THREAD

**Issue by TheCampingOwl** [ForgottenGlory/Dungeons-Deviousness#71]
If possible, please also attach a copy of your most recent save before the issue occurred.**
Not relevant

**D&D Version**
1.3.0

**Describe the bug**
Any animation that involves any sort of toy, both physical and magical variants, will not work, the SLALAnimObjBilyy.esp is missing from the install.

**To Reproduce**
Play any animation that involves any kind of toy, or just look in the installed files, the ESP is missing. DND\mods\Billy's SLAL animations

**Expected behavior**
For the ESP to be present and it's functions there.

**Screenshots**
Not possible in this situation.

**Additional context**
No.

**Comment by ForgottenGlory** [comment]
Fixed 1.4.0
