### ISSUE TITLE
Post-surrender animation issue. 

### ISSUE THREAD

**Issue by SomeKnowMeAsTim** [ForgottenGlory/Dungeons-Deviousness#72]
If possible, please also attach a copy of your most recent save before the issue occurred.**

**D&D Version**
1.3.0

**Describe the bug**
Character stuck in anim, legs open and close. Floating and moving in random directions. Only in 3rd person, 1st person is fine. 

**To Reproduce**
No idea, but reloading did not resolve issue, neither to last save or the one before that. Had to quit to desktop (no crash tho) Restarting game solved issue. 

**Expected behavior**
Not this. 

**Screenshots**
![ScreenShot291](https://user-images.githubusercontent.com/66573855/106211786-220d4280-617e-11eb-947a-bd82bffd63e1.png)

**Additional context**
Last two savegames attached. Suspect issue arose following reload post surrender in a fight when I got stuck in a kneeling anim but companions finished off enemy. 

[Save286_2C85D8B9_0_416C696120466C6F726973_Tamriel_010105_20210128230534_9_1.zip](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/5890764/Save286_2C85D8B9_0_416C696120466C6F726973_Tamriel_010105_20210128230534_9_1.zip)

**Comment by ForgottenGlory** [comment]
I've seen this before but have not been able to identify a cause or fix. Input welcome.
