### ISSUE TITLE
Bathing Breaking Devices

### ISSUE THREAD

**Issue by TheArQu** [ForgottenGlory/Dungeons-Deviousness#73]
**D&D Version**
1.3.0

**Describe the bug**
After re-equipping devices by keep it clean, you can equip armor over them,( or got some animation to try to unequip it, like cum drain) which renders them invisible and non-functional, you can unequip or equip them in inventory freely without prompts from DD and your follower will act like you don't have them.(they remain functional as long and you don't try to equip armor over them)

**To Reproduce**
1. get some restraints on you( I used DCL selfbondage for full set)
2. go to bath, interact with basket/use soap
3. equip normal armor/get cum drain animation playing
4. unequip armor, try to equip devices

**Expected behavior**
Devious Devices to work after bathing

**Screenshots**
Set for testing
![SkyrimSE_30_22_34_362](https://user-images.githubusercontent.com/30404650/106369197-9f3be180-634f-11eb-85be-9d77e4a7e8b7.jpg)
Equipped armor after bathing
![SkyrimSE_30_22_36_363](https://user-images.githubusercontent.com/30404650/106369196-9b0fc400-634f-11eb-9950-aa34d1b75e5d.jpg)
Broken Devices
![SkyrimSE_30_22_38_364](https://user-images.githubusercontent.com/30404650/106368998-4a4b9b80-634e-11eb-868b-20d125dc123e.jpg)

**Additional context**
idk, saves
[Saves.zip](https://github.com/ForgottenGlory/Dungeons-Deviousness/files/5898790/Saves.zip)

**Comment by xelphos** [comment]
Still preset in 1.4.0

**Comment by TheCampingOwl** [comment]
Known issue, it's caused by KCI(Keep it Clean), there is no way to fix it currently, keep the Keep It Clean mod turned off and you should not have those issues anymore.
