### ISSUE TITLE
BWA fatal error

### ISSUE THREAD

**Issue by TheCampingOwl** [ForgottenGlory/Dungeons-Deviousness#78]
**D&D Version**
1.4.0

**Describe the bug**
Enslaved a few NPC's, got error messages in the top left:
BWA: Actors need two unused face slots.
BWA: Face Slot allocation can be increased in nioverride.ini
BWA: Bandit Thug Beastmaster- Fatal Abort

Also, if you change cells with NPC's enslaved, their devious devices will no longer function properly, disable/enable in console doesn't fix it. There is also a specific option when interacting with them that isn't working, notably the 3rd, it involves the R word.

**To Reproduce**
Enslave any NPC or DM me for the save file

**Expected behavior**
Animations to adjust accordingly, the specific animations from the 3rd menu setting to trigger, and no BWA errors.

**Screenshots**
Not possible, i have them but not doable here, i can send them via DM.

**Additional context**
No

**Comment by PastyxCz** [comment]
Check in dnd/mods/racemenu/sksee.ini (or something like this) is bEnableFaceOverlays=1
Discovered this when i repair flickering lights, overalys must be 1

**Comment by TheCampingOwl** [comment]
It already is set to 1 by default, hence why I created this post.

**Comment by TheCampingOwl** [comment]
Fixed it by editing sksee64.ini, 

[Overlays/Face] ; "Face [Ovl#]" and "Face [SOvl#]"
; Determines how many face overlays there should be
iNumOverlays=5 ; Default[3]

It was set to 3 previously, seems that was causing issues.
