### ISSUE TITLE
Clitoral Piecing completely broken.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Dungeons-Deviousness#85]
**D&D Version**
1.4.0

**Describe the bug**
Basically, the first time you equip one it will give the lock prompt, but it won't actually lock, and then there after it will never promt to lock again. Example is if you get the cursed collar quest, at some point you need to equip one, but because they are broken, you get softlocked and cannot coninue the quest.

**To Reproduce**
Equip Clitoral piercing, doesn't matter as long as it's one that can lock. Then immediatly remove it. Won't ask for a key, nothing.

**Expected behavior**
Should function.To be clear, they do not function at all.

**Comment by TheCampingOwl** [comment]
Known issue, it's caused by KCI(Keep it Clean), there is no way to fix it currently, keep the Keep It Clean mod turned off and you should not have those issues anymore.

**Comment by xelphos** [comment]
> Known issue, it's caused by KCI(Keep it Clean), there is no way to fix it currently, keep the Keep It Clean mod turned off and you should not have those issues anymore.

I don't think it's just KIC. I recently did a new save did the whole MCM setup and then immediatly disabled it once out of the prison. Between Breezehome and Dragonsreach for me it broke. Only two things happened there. 

1. I recruited Abigail. 
2. I had a cursed loot event on a flower.

**Comment by xelphos** [comment]
Nevermind, It just broke again for me. No KIC enabled.

**Comment by xelphos** [comment]
I think I may have found one way it breaks. If you have one on and try to equip a different one, or the game tries to, they break,

**Comment by xelphos** [comment]
Thanks to Mercenar#1962 the actual cause was found.

The issue is caused by 3BBB, the slots needs to be changed from 50 to 60.
