### ISSUE TITLE
Ancono (College of Winterhold) Missing Armor

### ISSUE THREAD

**Issue by Space-Face** [ForgottenGlory/Dungeons-Deviousness#9]
**D&D Version**
Alpha 5

**Describe the bug**
When first meeting Ancono, he is missing his armor and appears nude (except he's also missing his male part).

**To Reproduce**
1. Go to college of winterhold and see him standing outside/in college buildings.

**Expected behavior**
Ancono has his armor and his bits.

**Comment by ForgottenGlory** [comment]
Can be fixed by going into the SOS MCM and clicking "De-schlongify armors"
