### ISSUE TITLE
Issue with FHU

### ISSUE THREAD

**Issue by zwasi** [ForgottenGlory/Dungeons-Deviousness#91]
Not sure what I did, but the belly node when inflated looks strange, couldn't figure out where the screenshots went but found one online.

(image removed)

**Comment by Shroud9** [comment]
Possible fix:

1. Download V1.4 of FHU Baka edition: https://www.loverslab.com/files/file/14920-fill-her-up-baka-edition/ (get file: 'Fill Her Up Baka Edition English SE 1.4V.7z')
2. Using MO2, install the mod and **_replace_** the pre-existing 'Filler Her Up Baka Edition English SE'. 
3. Disable 'Fill Her Body Morph Patch LE SE'. The pre-installed version of FHU Baka edition in the modpack was v1.2, which required this patch but v1.4 no longer does.
4. Disable 'SLSO FHU'. I heard on loverslab that this file causes some problems too.

If you're doing a clean install, just follow the instructions in the readme and you should be good.

If you already have an **existing save**: 
5. Load that save, go to FHU MCM menu, and click on 'reset quest'. Wait for a bit as the mod is reloaded. Once the mod setup is done, save your game and load that newly created save. 

Now you can configure FHU as you like and the mod should work properly. Well idk about you, but it works fine for me now.

![Capture](https://user-images.githubusercontent.com/79502013/108810767-d5831e80-75e6-11eb-9797-a5d0d358c5f6.PNG)

**Comment by TwistedModding** [comment]
If you are a user, please don't do anything said in this post, you'll break rule 11. As for the post creator. Take down the nude photo or the post entirely, or you'll be banned from the GitHub.
