### ISSUE TITLE
Deviously Cursed Loot SE last update removed previous version

### ISSUE THREAD

**Issue by LeFlemard** [ForgottenGlory/Dungeons-Deviousness#93]
**D&D Version**
 1.4.0

**Describe the bug**
As a new version of Deviously Cursed Loot came out, the mod author removed the previous file from download listing. This caused wabbajack to recognize the modlist as "failling" and render it not downloadable.

**To Reproduce**
Try to install the 1.4.0 version of this modlist.

**Expected behavior**
Actually being able to download the modlist.

**Additional context**
Modlist version of DCL should be updated to version 9.0.
Link to new version of DCL : https://mega.nz/file/7ZMAXbQD#cPR5m0k8q5ZTcL8WtYSgpeZS5tOhlRzhY4hMiUOcCyY

Thanks for taking up your time to read this.

**Comment by celadoneiron** [comment]
We are aware. There is no update planned for the current version of Dungeons & Deviousness to make it installable again, as work is focused on the rebuild of the list. You will need to wait until Dungeons & Deviousness: Director's Cut is available publicly.

**Comment by LeFlemard** [comment]
Thanks, I didn't saw any warnings so though the modlist's author had some serious life problems  or something.
