### ISSUE TITLE
Mod Suggestion for DnD

### ISSUE THREAD

**Issue by samtheknight10** [ForgottenGlory/Dungeons-Deviousness#94]
If it isn't currently being considered I would recommend the mod Radiant Prostitution/Gigolo. I played with it a little bit in Licentia before it was converted to osex. I think it could fit well in this list if it could work. I haven't played DnD yet so I don't have completed file but I'd like to when the Beta is released.

**Comment by ForgottenGlory** [comment]
I don't take suggestions for D&D.
