### ISSUE TITLE
One of the Chaurus tentacle attack animations causes CTD.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Dungeons-Deviousness#95]
**D&D Version**
D&D DC Beta 1

**Describe the bug**
After a spit attack from a chaurus triggers the tentacle attack you have a 50/50 chance to crash to desktop. You will go into third person as it's about to start, sometimes briefly before it crashes you will see stretched out tentacles.

**To Reproduce**
1. Find a place with chaurus.
2. Get spit on a bunch until it triggers.
3. If you get a certain animation you will crash. Not sure what the animations are called, but the animation where your character has the flesh thing attached to their back seems to work fine. It's the other one that crashes to desktop.

**Expected behavior**
Should play the animation as normal and not CTD.

**Screenshots**
I posted a video in the bug report channel on Discord, just skip to 2:30 in the video: https://canary.discord.com/channels/690583538210308106/848246716792176660/848790911886163978

**Comment by ForgottenGlory** [comment]
Fixed beta 2
