### ISSUE TITLE
Black Face Bug on Forge-Wife Ashaka in Markarth

### ISSUE THREAD

**Issue by ninjagaidenguy** [ForgottenGlory/Dungeons-Deviousness#97]
**D&D Version**
D&DDC Beta 1

**Describe the bug**
Black Face Bug on Forge-Wife Ashaka in Markarth

**To Reproduce**
Found here just walking around in Markarth.

**Expected behavior**
Face to look correct

**Screenshots**
![Capture](https://user-images.githubusercontent.com/512561/120221779-9a574380-c204-11eb-8f7c-18252bdcc6b2.PNG)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed beta 2
