### ISSUE TITLE
Missing mesh in the "Witch of the Wilds" starting area.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Dungeons-Deviousness#98]
**D&D Version**
Beta 2

**Describe the bug**
In the Witch of the Wilds scenario starting area, there's a missing mesh (white exclamation mark with red triangle) on one of the crafting platforms. See the attached screenshot for console info.

**To Reproduce**
Start in the Witch of the Wilds scenario, then go to the workbench with the missing mesh.

**Expected behavior**
There should be a mesh, not a big error triangle.

**Screenshots**
https://i.imgur.com/OrXuN4C.jpg

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
